//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiOrdNum.Models
{
    using System;
    
    public partial class Order01
    {
        public long EntryValue { get; set; }
    }
}
